### ISSUE TITLE
Remote link seems not longer supported.

### ISSUE THREAD

**Issue by jackalsin** [azu/gitbook-plugin-include-codeblock#62] opened 2017-12-28 23:00 UTC
The code I am using
```
[import, template:"acefull", title:"example of code", theme:"monokai"](https://raw.githubusercontent.com/jackalsin/Leetcode/master/src/main/java/example/binarySearch/BasicSolution.java)
```
The result:
![image](https://user-images.githubusercontent.com/14567001/34425354-c81ec17a-ebdf-11e7-9ac6-567e9703f2fc.png)

**Comment by azu** [comment] 2017-12-29 01:25
Duplicate of #42

**Closed as completed by azu** 2017-12-29 01:25 UTC
Labels: duplicate
